AWSTemplateFormatVersion: 2010-09-09
Description: >-
  view-count-api
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  DbSecretName:
    Type: String
    Description: Name of the Secrets Manager secret storing DB credentials

Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: add-project.js
  addProjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/add-project.addProjectHandler
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Adds a new project.
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DbSecretName}-*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-view-counts.js
  getViewCountsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-view-counts.getViewCountsHandler
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Gets all entries for view count data.
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DbSecretName}-*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: increment-view-count.js
  incrementViewCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/increment-view-count.incrementViewCountHandler
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Increments view count for an entry.
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DbSecretName}-*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: PATCH

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Test stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Test/"
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
